{% set name = "cwltool" %}
{% set version = "1.0.20181217162649" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 453e252525005b4c22dc654c0379227d516bf9364cce46184b580684cb50ad40

build:
  number: 1000
  entry_points:
    - cwltool=cwltool.main:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - bagit >=1.6.4
    - mypy_extensions
    - prov ==1.5.1
    - psutil
    - python
    - rdflib >=4.2.2
    - requests >=2.6.1
    - ruamel.yaml >=0.12.4,<=0.15.77
    - scandir
    - schema-salad >=3.0,<3.1
    - setuptools
    - shellescape >=3.4.1
    - six >=1.9.0
    - typing_extensions
    - pathlib2  # [py27]
    - typing  # [py27]
    - subprocess32  # [not win and py27]

test:
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help

about:
  home: https://www.commonwl.org/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  doc_url: https://github.com/common-workflow-language/cwltool 

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
